allowBuild: '@prisma/client,@prisma/engines,prisma,esbuild,sharp'

ignoredBuiltDependencies:
  - puppeteer
  - unrs-resolver

onlyBuiltDependencies:
  - ','
  - '@'
  - /
  - a
  - b
  - c
  - d
  - e
  - g
  - h
  - i
  - l
  - m
  - n
  - p
  - r
  - s
  - t
  - u
